In [1]:
import pickle as pk

In [2]:
pk.load(open('./federated_local_predictor_noise001_validation_loss.pk', 'rb'))

{5: 6.556320135007176,
 10: 4.805603113247413,
 15: 3.320689453618585,
 20: 3.0447374208731786,
 25: 2.6679516471980214,
 30: 2.4854355017980563,
 35: 2.356325781360135,
 40: 2.463917662334222,
 45: 2.335360666229164,
 50: 2.252672481005031,
 55: 2.273030526738914,
 60: 2.1413257526597618,
 65: 2.090080380244885,
 70: 2.127337074212957,
 75: 2.1836552837735534,
 80: 2.1291974867149857,
 85: 2.1055904451724383,
 90: 2.089782991189215,
 95: 2.0609875967206617,
 100: 2.061955857756433,
 105: 2.0139927005231377,
 110: 1.9745659937416367,
 115: 2.0418864998395967,
 120: 1.956823738802479,
 125: 1.9330442027673806,
 130: 1.9499376327653066,
 135: 1.941154570893985,
 140: 1.9901906512775416,
 145: 1.9437485999753008,
 150: 1.955717184672501,
 155: 1.896387821897901,
 160: 1.8721922528819945,
 165: 1.9226190244742523,
 170: 1.8403634698576978,
 175: 1.9453599659061207,
 180: 1.8932206600352068,
 185: 1.9100892744805786,
 190: 1.9562585828365493,
 195: 1.8785925335268168,
 200: 1.88156993048782

In [3]:
pk.load(open('./results_tokyo/evaluation_local_nll.pk', 'rb'))

{(2012, 12, 1, 0): 0.37996920603321116,
 (2012, 12, 1, 1): 0.3643399616113528,
 (2012, 12, 1, 2): 0.3360281821595591,
 (2012, 12, 1, 3): 0.3092003407185538,
 (2012, 12, 1, 4): 0.28972609251946085,
 (2012, 12, 1, 5): 0.27918825551763776,
 (2012, 12, 1, 6): 0.29152129766781903,
 (2012, 12, 1, 7): 0.29082039096056916,
 (2012, 12, 1, 8): 0.2862245295067045,
 (2012, 12, 1, 9): 0.23505731126350543,
 (2012, 12, 1, 10): 0.2595776950226919,
 (2012, 12, 1, 11): 0.25283348467354594,
 (2012, 12, 1, 12): 0.29823916259583916,
 (2012, 12, 1, 13): 0.3127899472374957,
 (2012, 12, 1, 14): 0.38145742549162825,
 (2012, 12, 1, 15): 0.47736341468375515,
 (2012, 12, 1, 16): 0.53496770388141,
 (2012, 12, 1, 17): 0.6365481474002203,
 (2012, 12, 1, 18): 0.7373760451577501,
 (2012, 12, 1, 19): 0.8144136414180132,
 (2012, 12, 1, 20): 1.0041504218165158,
 (2012, 12, 1, 21): 1.0695033163481156,
 (2012, 12, 1, 22): 1.2033157306236204,
 (2012, 12, 1, 23): 1.4084062596961173,
 (2012, 12, 1, 24): 1.4332785502420666,
 (

In [4]:
import numpy as np

In [5]:
with open('./results_tokyo/evaluation_local_nll.pk', 'rb') as f:
    nll_tokyo_1 = pk.load(f)
with open('./results_tokyo/evaluation_local_broader_nll.pk', 'rb') as f:
    nll_tokyo_3 = pk.load(f)
with open('./results_osaka/evaluation_local_nll.pk', 'rb') as f:
    nll_osaka_1 = pk.load(f)
with open('./results_osaka/evaluation_local_broader_nll.pk', 'rb') as f:
    nll_osaka_3 = pk.load(f)

In [6]:
with open('./results_tokyo/evaluation_local_rank.pk', 'rb') as f:
    rank_tokyo_1 = pk.load(f)
with open('./results_tokyo/evaluation_local_broader_rank.pk', 'rb') as f:
    rank_tokyo_3 = pk.load(f)
with open('./results_osaka/evaluation_local_rank.pk', 'rb') as f:
    rank_osaka_1 = pk.load(f)
with open('./results_osaka/evaluation_local_broader_rank.pk', 'rb') as f:
    rank_osaka_3 = pk.load(f)

In [7]:
rank_osaka_3

{(2012, 12, 1): (0.8163684418876461, 19.030792381323934, 0.8755695197224506),
 (2012, 12, 2): (0.8254409245301642, 18.140035219355333, 0.8811193629890514),
 (2012, 12, 3): (0.8306462526080254, 15.077683913875141, 0.8912003158546796),
 (2012, 12, 4): (0.8290136646373787, 15.833400328389326, 0.8907458252996041),
 (2012, 12, 5): (0.829894904418559, 15.585905065750454, 0.8918270377869126),
 (2012, 12, 6): (0.8266329281003995, 15.930655282586816, 0.8878298872624846),
 (2012, 12, 7): (0.819822027973649, 16.871064118602114, 0.8820034068829683),
 (2012, 12, 8): (0.8150265929836497, 19.246866255496546, 0.8741219804694192),
 (2012, 12, 9): (0.8235670312520917, 18.09352747783543, 0.8805762009380015),
 (2012, 12, 10): (0.8298226546120226, 16.131469437248526, 0.8895786253651546),
 (2012, 12, 11): (0.8243468092664097, 16.93515180590775, 0.8860256322390515),
 (2012, 12, 12): (0.8232304026404379, 17.324877599295853, 0.8846063923423919),
 (2012, 12, 13): (0.8233952167840712, 17.492651139844185, 0.88430

In [8]:
nll_osaka_3

{(2012, 12, 1, 0): tensor(0.3567, device='cuda:1'),
 (2012, 12, 1, 1): tensor(0.3899, device='cuda:1'),
 (2012, 12, 1, 2): tensor(0.3694, device='cuda:1'),
 (2012, 12, 1, 3): tensor(0.3577, device='cuda:1'),
 (2012, 12, 1, 4): tensor(0.3423, device='cuda:1'),
 (2012, 12, 1, 5): tensor(0.2910, device='cuda:1'),
 (2012, 12, 1, 6): tensor(0.3368, device='cuda:1'),
 (2012, 12, 1, 7): tensor(0.2828, device='cuda:1'),
 (2012, 12, 1, 8): tensor(0.2507, device='cuda:1'),
 (2012, 12, 1, 9): tensor(0.2977, device='cuda:1'),
 (2012, 12, 1, 10): tensor(0.2350, device='cuda:1'),
 (2012, 12, 1, 11): tensor(0.2264, device='cuda:1'),
 (2012, 12, 1, 12): tensor(0.2516, device='cuda:1'),
 (2012, 12, 1, 13): tensor(0.2917, device='cuda:1'),
 (2012, 12, 1, 14): tensor(0.3934, device='cuda:1'),
 (2012, 12, 1, 15): tensor(0.3325, device='cuda:1'),
 (2012, 12, 1, 16): tensor(0.4904, device='cuda:1'),
 (2012, 12, 1, 17): tensor(0.5160, device='cuda:1'),
 (2012, 12, 1, 18): tensor(0.5881, device='cuda:1'),
 (2

In [5]:
def filter_and_average(results, dtype=None):
    metrics = []
    for dt in results:
        if len(dt) == 3:
            if dtype is None:
                metrics.append(results[dt])
            else:
                metrics.append(results[dt].item())
    metrics = np.array(metrics)
    return np.mean(metrics, axis=0)

In [13]:
filter_and_average(rank_osaka_1)

array([ 0.81677663, 22.80592388,  0.87478645])

In [14]:
filter_and_average(rank_osaka_3)

array([ 0.81947933, 21.54087987,  0.87739698])

In [15]:
filter_and_average(rank_tokyo_1)

array([ 0.82577475, 18.53875315,  0.87943513])

In [16]:
filter_and_average(rank_tokyo_3)

array([ 0.82781784, 17.4123825 ,  0.88185596])

In [8]:
filter_and_average(nll_osaka_1)

1.393391314901104

In [22]:
filter_and_average(nll_osaka_3, dtype='tensor')

1.3633036692937215

In [6]:
filter_and_average(nll_tokyo_1)

1.3149417389203837

In [25]:
filter_and_average(nll_tokyo_3, dtype='tensor')

1.288557023472256